name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  unit_tests:
    runs-on: macos-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v3
    - name: Build 
      run: swift build
    - name: Run tests
      run: swift test